---
apiVersion: v1
kind: Pod
metadata:
  name: todobackend
  labels:
    app: todobackend
spec:
  containers:
    - name: todobackend
      image: 348807118004.dkr.ecr.ap-southeast-2.amazonaws.com/aws-learn-devops/todobackend
      imagePullPolicy: IfNotPresent
      command:
        - uwsgi
        - "--http=0.0.0.0:8000"
        - "--module=todobackend.wsgi"
        - "--master"
        - "--die-on-term"
        - "--processes=4"
        - "--threads=2"
        - "--check-static=/public"
      env:
        - name: DJANGO_SETTINGS_MODULE
          value: todobackend.settings_release
